from app.modelos import *

naturalezas: list[Naturaleza] = [
    Naturaleza(
        id=1,
        nombre="Fuerte",
        stat_perjudicada_id=2,
        stat_mejorada_id=2
        ),
    Naturaleza(
        id=2,
        nombre="Osada",
        stat_perjudicada_id=2,
        stat_mejorada_id=3
        ),
    Naturaleza(
        id=3,
        nombre="Modesta",
        stat_perjudicada_id=2,
        stat_mejorada_id=4
        ),
    Naturaleza(
        id=4,
        nombre="Serena",
        stat_perjudicada_id=2,
        stat_mejorada_id=5
        ),
    Naturaleza(
        id=5,
        nombre="Miedosa",
        stat_perjudicada_id=2,
        stat_mejorada_id=6
        ),
    Naturaleza(
        id=6,
        nombre="Huraña",
        stat_perjudicada_id=3,
        stat_mejorada_id=2
        ),
    Naturaleza(
        id=7,
        nombre="Dócil",
        stat_perjudicada_id=3,
        stat_mejorada_id=3
        ),
    Naturaleza(
        id=8,
        nombre="Afable",
        stat_perjudicada_id=3,
        stat_mejorada_id=4
        ),
    Naturaleza(
        id=9,
        nombre="Amable",
        stat_perjudicada_id=3,
        stat_mejorada_id=5
        ),
    Naturaleza(
        id=10,
        nombre="Activa",
        stat_perjudicada_id=3,
        stat_mejorada_id=6
        ),
    Naturaleza(
        id=11,
        nombre="Firme",
        stat_perjudicada_id=4,
        stat_mejorada_id=2
        ),
    Naturaleza(
        id=12,
        nombre="Agitada",
        stat_perjudicada_id=4,
        stat_mejorada_id=3
        ),
    Naturaleza(
        id=13,
        nombre="Tímida",
        stat_perjudicada_id=4,
        stat_mejorada_id=4
        ),
    Naturaleza(
        id=14,
        nombre="Cauta",
        stat_perjudicada_id=4,
        stat_mejorada_id=5
        ),
    Naturaleza(
        id=15,
        nombre="Alocada",
        stat_perjudicada_id=5,
        stat_mejorada_id=4
        ),
    Naturaleza(
        id=16,
        nombre="Alegre",
        stat_perjudicada_id=4,
        stat_mejorada_id=6
        ),
    Naturaleza(
        id=17,
        nombre="Pícara",
        stat_perjudicada_id=5,
        stat_mejorada_id=2
        ),
    Naturaleza(
        id=18,
        nombre="Floja",
        stat_perjudicada_id=5,
        stat_mejorada_id=3
        ),
    Naturaleza(
        id=19,
        nombre="Rara",
        stat_perjudicada_id=5,
        stat_mejorada_id=5
        ),
    Naturaleza(
        id=20,
        nombre="Ingenua",
        stat_perjudicada_id=5,
        stat_mejorada_id=6
        ),
    Naturaleza(
        id=21,
        nombre="Audaz",
        stat_perjudicada_id=6,
        stat_mejorada_id=2
        ),
    Naturaleza(
        id=22,
        nombre="Plácida",
        stat_perjudicada_id=6,
        stat_mejorada_id=3
        ),
    Naturaleza(
        id=23,
        nombre="Mansa",
        stat_perjudicada_id=6,
        stat_mejorada_id=4
        ),
    Naturaleza(
        id=24,
        nombre="Grosera",
        stat_perjudicada_id=6,
        stat_mejorada_id=5
        ),
    Naturaleza(
        id=25,
        nombre="Seria",
        stat_perjudicada_id=6,
        stat_mejorada_id=6
        ),
]